# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61950a386d0bbfa6bbfd0a64d00bd0064f99c1c3f76c3364621e9b79101441022fa37815daa86bedaf6fd7ca1eb8b9da7a9531775bead6ba1055c16fdb77da5b

test:
  secret_key_base: c1caa8b4af900972720b3887abd5d2df13873b7ff63c5f2c09a342e0d9f9ba593c6e4da61476521746fe5a6a3d5c8b64915e89374b3c7e0e5d9e788e1a71c64a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
